# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20170622_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='short_bio',
            field=models.TextField(default='blah blah blah'),
            preserve_default=False,
        ),
    ]
