# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_watsonpersonalitytone_json_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watsonpersonalitytone',
            name='json_test',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='election_year',
            field=models.CharField(choices=[('1932', '1932'), ('1960', '1960'), ('1980', '1980'), ('2004', '2004'), ('2008', '2008'), ('2016', '2016')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party_name',
            field=models.CharField(choices=[('Democrat', 'Democrat'), ('Republican', 'Republican')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Election',
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
